source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

gem 'rails', '~> 7.0.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'

# スクレイピング・HTTP通信
gem 'nokogiri'
gem 'faraday'
gem 'mechanize'

# 環境変数
gem 'dotenv-rails'

# JSON処理
gem 'jbuilder'

# CORS対応
gem 'rack-cors'

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'web-console'
end
