services:
  # Webサービス（Rails API）
  - type: web
    name: note-automation-api
    env: ruby
    plan: free
    region: oregon
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec rails server -p $PORT -e $RAILS_ENV
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: note-automation-db
          property: connectionString
      - key: NOTE_EMAIL
        sync: false
      - key: NOTE_PASSWORD
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false

  # データベース
  - type: pgsql
    name: note-automation-db
    plan: free
    region: oregon

  # 定期実行ジョブ（記事作成）
  - type: cron
    name: create-draft-job
    env: ruby
    plan: free
    schedule: "0 */3 * * *"  # 3時間ごと
    buildCommand: bundle install
    startCommand: curl -X POST https://note-automation-api.onrender.com/api/automation/create_draft

  # 定期実行ジョブ（フォロー）
  - type: cron
    name: follow-users-job
    env: ruby
    plan: free
    schedule: "30 */3 * * *"  # 3時間ごと（30分ずらし）
    buildCommand: bundle install
    startCommand: curl -X POST https://note-automation-api.onrender.com/api/automation/follow_users
