name: Like Unliked Notes

on:
  schedule:
    # https://note.com/mo_ru_co/n/n005f10270107
    # 1. 短時間でのスキ数制限
    # • 30分以内に24回以上のスキを押すと制限がかかる場合があります。
    # 2. 1日のスキ数制限
    # • 24時間以内に200回以上のスキを押すと制限対象になることがあります。
    - cron: '0 0 * * *'    # 毎日9:00(JST)
    - cron: '0 3 * * *'    # 毎日12:00(JST)
    - cron: '0 6 * * *'    # 毎日15:00(JST)
    - cron: '0 9 * * *'    # 毎日18:00(JST)
    - cron: '0 12 * * *'   # 毎日21:00(JST)
    - cron: '0 15 * * *'   # 毎日0:00(JST)
    - cron: '0 18 * * *'   # 毎日3:00(JST)
    - cron: '0 21 * * *'   # 毎日6:00(JST)
  workflow_dispatch:

jobs:
  like-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm install
      - name: Run likeUnlikedNotes.js
        env:
          NOTE_EMAIL: ${{ secrets.NOTE_EMAIL }}
          NOTE_PASSWORD: ${{ secrets.NOTE_PASSWORD }}
        run: node likeUnlikedNotes.js 
